[project]
name = "time-series-momentum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "joblib>=1.6.0",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "yfinance>=1.7.0",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
